using System;
using System.Collections.Generic;

namespace softire.api.Models
{
    public partial class SnConfiguracion
    {
        public SnConfiguracion()
        {
            SnVehiculo = new HashSet<SnVehiculo>();
        }

        public string CodCia { get; set; }
        public string CodConfi { get; set; }
        public string Descripcion { get; set; }
        public string Eje01 { get; set; }
        public string Eje02 { get; set; }
        public string Eje03 { get; set; }
        public string Eje04 { get; set; }
        public string Eje05 { get; set; }
        public string Eje06 { get; set; }
        public string Eje07 { get; set; }
        public string Eje08 { get; set; }
        public string Eje09 { get; set; }
        public string Eje10 { get; set; }
        public string Eje010 { get; set; }
        public string Coro01 { get; set; }
        public string Coro02 { get; set; }
        public string Coro03 { get; set; }
        public string Coro04 { get; set; }
        public string Coro05 { get; set; }
        public string Coro06 { get; set; }
        public string Coro07 { get; set; }
        public string Coro08 { get; set; }
        public string Coro09 { get; set; }
        public string Coro10 { get; set; }
        public string Coro010 { get; set; }
        public string TipoEje01 { get; set; }
        public string TipoEje02 { get; set; }
        public string TipoEje03 { get; set; }
        public string TipoEje04 { get; set; }
        public string TipoEje05 { get; set; }
        public string TipoEje06 { get; set; }
        public string TipoEje07 { get; set; }
        public string TipoEje08 { get; set; }
        public string TipoEje09 { get; set; }
        public string TipoEje10 { get; set; }
        public decimal? Nr01 { get; set; }
        public decimal? Nr02 { get; set; }
        public decimal? Nr03 { get; set; }
        public decimal? Nr04 { get; set; }
        public string Foto101 { get; set; }
        public string Foto102 { get; set; }
        public string Foto103 { get; set; }
        public string Foto104 { get; set; }
        public string Foto105 { get; set; }
        public string Foto106 { get; set; }
        public string Foto107 { get; set; }
        public string Foto108 { get; set; }
        public string Foto201 { get; set; }
        public string Foto202 { get; set; }
        public string Foto203 { get; set; }
        public string Foto204 { get; set; }
        public string Foto205 { get; set; }
        public string Foto206 { get; set; }
        public string Foto207 { get; set; }
        public string Foto208 { get; set; }
        public string Foto301 { get; set; }
        public string Foto302 { get; set; }
        public string Foto303 { get; set; }
        public string Foto304 { get; set; }
        public string Foto305 { get; set; }
        public string Foto306 { get; set; }
        public string Foto307 { get; set; }
        public string Foto308 { get; set; }
        public string Foto401 { get; set; }
        public string Foto402 { get; set; }
        public string Foto403 { get; set; }
        public string Foto404 { get; set; }
        public string Foto405 { get; set; }
        public string Foto406 { get; set; }
        public string Foto407 { get; set; }
        public string Foto408 { get; set; }
        public string Foto501 { get; set; }
        public string Foto502 { get; set; }
        public string Foto503 { get; set; }
        public string Foto504 { get; set; }
        public string Foto505 { get; set; }
        public string Foto506 { get; set; }
        public string Foto507 { get; set; }
        public string Foto508 { get; set; }
        public string Foto601 { get; set; }
        public string Foto602 { get; set; }
        public string Foto603 { get; set; }
        public string Foto604 { get; set; }
        public string Foto605 { get; set; }
        public string Foto606 { get; set; }
        public string Foto607 { get; set; }
        public string Foto608 { get; set; }
        public string Foto701 { get; set; }
        public string Foto702 { get; set; }
        public string Foto703 { get; set; }
        public string Foto704 { get; set; }
        public string Foto705 { get; set; }
        public string Foto706 { get; set; }
        public string Foto707 { get; set; }
        public string Foto708 { get; set; }
        public string Foto801 { get; set; }
        public string Foto802 { get; set; }
        public string Foto803 { get; set; }
        public string Foto804 { get; set; }
        public string Foto805 { get; set; }
        public string Foto806 { get; set; }
        public string Foto807 { get; set; }
        public string Foto808 { get; set; }
        public string Foto901 { get; set; }
        public string Foto902 { get; set; }
        public string Foto903 { get; set; }
        public string Foto904 { get; set; }
        public string Foto905 { get; set; }
        public string Foto906 { get; set; }
        public string Foto907 { get; set; }
        public string Foto908 { get; set; }
        public string Foto1001 { get; set; }
        public string Foto1002 { get; set; }
        public string Foto1003 { get; set; }
        public string Foto1004 { get; set; }
        public string Foto1005 { get; set; }
        public string Foto1006 { get; set; }
        public string Foto1007 { get; set; }
        public string Foto1008 { get; set; }
        public string Fotor01 { get; set; }
        public string Fotor02 { get; set; }
        public string Fotor03 { get; set; }
        public string Fotor04 { get; set; }
        public decimal? N101 { get; set; }
        public decimal? N102 { get; set; }
        public decimal? N103 { get; set; }
        public decimal? N104 { get; set; }
        public decimal? N105 { get; set; }
        public decimal? N106 { get; set; }
        public decimal? N107 { get; set; }
        public decimal? N108 { get; set; }
        public decimal? N201 { get; set; }
        public decimal? N202 { get; set; }
        public decimal? N203 { get; set; }
        public decimal? N204 { get; set; }
        public decimal? N205 { get; set; }
        public decimal? N206 { get; set; }
        public decimal? N207 { get; set; }
        public decimal? N208 { get; set; }
        public decimal? N301 { get; set; }
        public decimal? N302 { get; set; }
        public decimal? N303 { get; set; }
        public decimal? N304 { get; set; }
        public decimal? N305 { get; set; }
        public decimal? N306 { get; set; }
        public decimal? N307 { get; set; }
        public decimal? N308 { get; set; }
        public decimal? N401 { get; set; }
        public decimal? N402 { get; set; }
        public decimal? N403 { get; set; }
        public decimal? N404 { get; set; }
        public decimal? N405 { get; set; }
        public decimal? N406 { get; set; }
        public decimal? N407 { get; set; }
        public decimal? N408 { get; set; }
        public decimal? N501 { get; set; }
        public decimal? N502 { get; set; }
        public decimal? N503 { get; set; }
        public decimal? N504 { get; set; }
        public decimal? N505 { get; set; }
        public decimal? N506 { get; set; }
        public decimal? N507 { get; set; }
        public decimal? N508 { get; set; }
        public decimal? N601 { get; set; }
        public decimal? N602 { get; set; }
        public decimal? N603 { get; set; }
        public decimal? N604 { get; set; }
        public decimal? N605 { get; set; }
        public decimal? N606 { get; set; }
        public decimal? N607 { get; set; }
        public decimal? N608 { get; set; }
        public decimal? N701 { get; set; }
        public decimal? N702 { get; set; }
        public decimal? N703 { get; set; }
        public decimal? N704 { get; set; }
        public decimal? N705 { get; set; }
        public decimal? N706 { get; set; }
        public decimal? N707 { get; set; }
        public decimal? N708 { get; set; }
        public decimal? N801 { get; set; }
        public decimal? N802 { get; set; }
        public decimal? N803 { get; set; }
        public decimal? N804 { get; set; }
        public decimal? N805 { get; set; }
        public decimal? N806 { get; set; }
        public decimal? N807 { get; set; }
        public decimal? N808 { get; set; }
        public decimal? N901 { get; set; }
        public decimal? N902 { get; set; }
        public decimal? N903 { get; set; }
        public decimal? N904 { get; set; }
        public decimal? N905 { get; set; }
        public decimal? N906 { get; set; }
        public decimal? N907 { get; set; }
        public decimal? N908 { get; set; }
        public decimal? N1001 { get; set; }
        public decimal? N1002 { get; set; }
        public decimal? N1003 { get; set; }
        public decimal? N1004 { get; set; }
        public decimal? N1005 { get; set; }
        public decimal? N1006 { get; set; }
        public decimal? N1007 { get; set; }
        public decimal? N1008 { get; set; }
        public string Nota { get; set; }
        public string Breve { get; set; }
        public string Estado { get; set; }
        public DateTime? Fecha { get; set; }
        public string Usuario { get; set; }

        public virtual SnCiaNeumatico CodCiaNavigation { get; set; }
        public virtual ICollection<SnVehiculo> SnVehiculo { get; set; }
    }
}
